logo: # add logo name
title: 黄黄跨越太平洋
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/wlx" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.png
author-name: 黄黄
about-author: 前四大高管黄黄，为您讲述自己成功移民新西兰的真实故事。分享移民相关政策和解析干货、记录在新西兰生活的趣事糗事、感叹新西兰教育的独特魅力、领略世界最后净土的无限美景、再吐槽吐槽偶尔遇上的怪人怪事，带您跨过南太平洋，发现新西兰，了解新西兰。
email: huanghuangnz@gmail.com
phone: # your pnone number
website: https://huanghuangnz.github.io/wlx/ # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: huanghuangnz # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

prose:
  rooturl: '_posts'
  siteurl: 'https://huanghuangnz.github.io/wlx'
  media: 'assets/img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "img"
        field:
          element: "text"
          label: "img"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "wls"
              value: "微留学"
            - name: "blog"
              value: "见闻"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
